name: CI/CD to Yandex Cloud

on:
  push:
    branches: [ main ]
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install YC CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate in Yandex Cloud
        run: |
          echo '${{ secrets.YC_SA_KEY_JSON }}' > key.json
          yc config set service-account-key key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

      - name: Get YCR Docker credentials
        run: |
          yc container registry configure-docker

      - name: Set image tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="latest"
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push Docker image to YCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: cr.yandex/${{ secrets.YC_REGISTRY }}/myapp:${{ env.IMAGE_TAG }}

  deploy:
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Decode kubeconfig and configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy to Kubernetes
        env:
          IMAGE: cr.yandex/${{ secrets.YC_REGISTRY }}/myapp:${{ env.IMAGE_TAG }}
        run: |
          kubectl set image deployment/my-deployment my-container=${IMAGE} --record
